import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <footer className="border-t border-white/5 bg-black/10 py-6 mt-12">
          <div className="mx-auto max-w-7xl px-6 text-zinc-300 text-sm text-center">© {new Date().getFullYear()} House Party — Made for good vibes. <span className="ml-2">Contact: hello@houseparty.local</span></div>
        </footer>
      </body>
    </html>
  );
}
